services:
  broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "1884:1884"
      - "9001:9001"
    volumes:
      - type: bind
        source: mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
  mockserver:
    image: mockserver/mockserver:5.14.0
    ports:
      - "1080:1080"
    command: -logLevel DEBUG -serverPort 1080
