name: prepare
description: prepare for build
outputs:
  random-number:
    description: "version of artifact as declared in gradle file"
    value: ${{ steps.version_step.outputs.artifact_version }}
runs:
  using: composite
  steps:
    - name: Checkout project sources
      uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '17'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Extract version
      id: version_step
      shell: bash
      run: ./gradlew properties -q | awk '/^version:/ {print "artifact_version="$2}' >> $GITHUB_OUTPUT
